In [193]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [194]:
df=pd.read_csv(r"C:\Kanishka\My Programs\Python\MACHINE LEARNING\CSV FILES\Housing.csv")
df.tail()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [195]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()
df["mainroad"]=oe.fit_transform(df[["mainroad"]])
df["basement"]=oe.fit_transform(df[["basement"]])
df["guestroom"]=oe.fit_transform(df[["guestroom"]])
df["hotwaterheating"]=oe.fit_transform(df[["hotwaterheating"]])
df["airconditioning"]=oe.fit_transform(df[["airconditioning"]])
df[["prefarea"]]=oe.fit_transform(df[["prefarea"]])

df.head(30)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1.0,0.0,0.0,0.0,1.0,2,1.0,furnished
1,12250000,8960,4,4,4,1.0,0.0,0.0,0.0,1.0,3,0.0,furnished
2,12250000,9960,3,2,2,1.0,0.0,1.0,0.0,0.0,2,1.0,semi-furnished
3,12215000,7500,4,2,2,1.0,0.0,1.0,0.0,1.0,3,1.0,furnished
4,11410000,7420,4,1,2,1.0,1.0,1.0,0.0,1.0,2,0.0,furnished
5,10850000,7500,3,3,1,1.0,0.0,1.0,0.0,1.0,2,1.0,semi-furnished
6,10150000,8580,4,3,4,1.0,0.0,0.0,0.0,1.0,2,1.0,semi-furnished
7,10150000,16200,5,3,2,1.0,0.0,0.0,0.0,0.0,0,0.0,unfurnished
8,9870000,8100,4,1,2,1.0,1.0,1.0,0.0,1.0,2,1.0,furnished
9,9800000,5750,3,2,4,1.0,1.0,0.0,0.0,1.0,1,1.0,unfurnished
10,9800000,13200,3,1,2,1.0,0.0,1.0,0.0,1.0,2,1.0,furnished
11,9681000,6000,4,3,2,1.0,1.0,1.0,1.0,0.0,2,0.0,semi-furnished
12,9310000,6550,4,2,2,1.0,0.0,0.0,0.0,1.0,1,1.0,semi-furnished
13,9240000,3500,4,2,2,1.0,0.0,0.0,1.0,0.0,2,0.0,furnished
14,9240000,7800,3,2,2,1.0,0.0,0.0,0.0,0.0,0,1.0,semi-furnished
15,9100000,6000,4,1,2,1.0,0.0,1.0,0.0,0.0,2,0.0,semi-furnished
16,9100000,6600,4,2,2,1.0,1.0,1.0,0.0,1.0,1,1.0,unfurnished
17,8960000,8500,3,2,4,1.0,0.0,0.0,0.0,1.0,2,0.0,furnished
18,8890000,4600,3,2,2,1.0,1.0,0.0,0.0,1.0,2,0.0,furnished
19,8855000,6420,3,2,2,1.0,0.0,0.0,0.0,1.0,1,1.0,semi-furnished
20,8750000,4320,3,1,2,1.0,0.0,1.0,1.0,0.0,2,0.0,semi-furnished
21,8680000,7155,3,2,1,1.0,1.0,1.0,0.0,1.0,2,0.0,unfurnished
22,8645000,8050,3,1,1,1.0,1.0,1.0,0.0,1.0,1,0.0,furnished
23,8645000,4560,3,2,2,1.0,1.0,1.0,0.0,1.0,1,0.0,furnished
24,8575000,8800,3,2,2,1.0,0.0,0.0,0.0,1.0,2,0.0,furnished
25,8540000,6540,4,2,2,1.0,1.0,1.0,0.0,1.0,2,1.0,furnished
26,8463000,6000,3,2,4,1.0,1.0,1.0,0.0,1.0,0,1.0,semi-furnished
27,8400000,8875,3,1,1,1.0,0.0,0.0,0.0,0.0,1,0.0,semi-furnished
28,8400000,7950,5,2,2,1.0,0.0,1.0,1.0,0.0,2,0.0,unfurnished
29,8400000,5500,4,2,2,1.0,0.0,1.0,0.0,1.0,1,1.0,semi-furnished

In [196]:


status = pd.get_dummies(df['furnishingstatus'])
status = pd.get_dummies(df['furnishingstatus'], drop_first = True,dtype=int)
df= pd.concat([df, status], axis = 1)
df.drop(["furnishingstatus"],axis=1,inplace=True)
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,semi-furnished,unfurnished
0,13300000,7420,4,2,3,1.0,0.0,0.0,0.0,1.0,2,1.0,0,0
1,12250000,8960,4,4,4,1.0,0.0,0.0,0.0,1.0,3,0.0,0,0
2,12250000,9960,3,2,2,1.0,0.0,1.0,0.0,0.0,2,1.0,1,0
3,12215000,7500,4,2,2,1.0,0.0,1.0,0.0,1.0,3,1.0,0,0
4,11410000,7420,4,1,2,1.0,1.0,1.0,0.0,1.0,2,0.0,0,0

In [197]:
X=df.iloc[:,1:].values
y=df.iloc[:,1].values

In [198]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [199]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=100,random_state=42)
regressor.fit(X_train,y_train)

RandomForestRegressor(random_state=42)

In [200]:
y_pred=regressor.predict(X_test)

In [201]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9996609320634497